name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
      name: Build and push fula dev
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/fula-dev:latest
    -
      name: Build and push box
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./apps/box/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/box:latest
