name: Test Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    services:
        ipfs:
          image: ipfs/ipfs-cluster-test:v1.0.1
          ports:
            - "4001:4001" # ipfs swarm - expose if needed/wanted
            - "5001:5001" # ipfs api - expose if needed/wanted
            - "8080:8080" # ipfs gateway - expose if needed/wanted
            - "9094:9094"
            - "9095:9095"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install -g @microsoft/rush
      - run: rush update
      - run: rush build
      - name: Run Tests
        env:
          FULA_IPFS_HTTP: "http://ipfs:5001"
          FULA_CLUSTER_PROXY: "http://ipfs:9095"
        working-directory: ./apps/box
        run: rushx test
